### PR TITLE
Feature/react deprecation stuff

### LINKED ISSUE #21: proptypes deprecation issue

### PR DESCRIPTION
**Pull request by vladimirlogachev**
fixed #21

### CODE REVIEW

**Comment by vladimirlogachev** [comment]
fixed issue #27

**Comment by vladimirlogachev** [comment]
Solved issue #26 rimraf

**Comment by mkarabashev** [comment]
Is there a reason for the removal of the dev tools?

**Comment by vladimirlogachev** [comment]
Yes. I will get them back when absolutely necessary. Git remembers everything, so it will be easy.

**Comment by ksmai** [comment]
partially solved issue #29

**Pull request merged**
